# Generated by Django 2.0.2 on 2018-03-02 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='name',
            field=models.CharField(default='Ole', max_length=100),
            preserve_default=False,
        ),
    ]
