# Generated by Django 2.0.2 on 2018-03-02 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='location',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='venue',
            unique_together={('name', 'location')},
        ),
    ]
