# Generated by Django 2.0.2 on 2018-03-04 21:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.CharField(default='Description', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='when',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 4, 21, 5, 21, 969407)),
        ),
    ]
